# Generated by Django 2.0.7 on 2018-07-28 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(default=django.utils.timezone.now, unique=True)),
                ('cluster_description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cluster Data',
                'verbose_name_plural': 'Cluster Data',
                'ordering': ('cluster_id',),
            },
        ),
        migrations.CreateModel(
            name='ErrorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(default=django.utils.timezone.now, max_length=10, unique=True)),
                ('error_description', models.CharField(max_length=200)),
                ('error_mitigation', models.CharField(max_length=1000)),
                ('screenshot_link', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('error_validated', models.BooleanField(default=False)),
                ('error_validator', models.CharField(max_length=200)),
                ('editors_list', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Error Data',
                'verbose_name_plural': 'Error Data',
                'ordering': ('error_id',),
            },
        ),
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(default=django.utils.timezone.now, max_length=10, unique=True)),
                ('module_description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Module Data',
                'verbose_name_plural': 'Module Data',
                'ordering': ('module_id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default=django.utils.timezone.now, max_length=10, unique=True)),
                ('project_description', models.CharField(max_length=200)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.ClusterData', to_field='cluster_id')),
            ],
            options={
                'verbose_name': 'Project Data',
                'verbose_name_plural': 'Project Data',
                'ordering': ('project_id',),
            },
        ),
        migrations.AddField(
            model_name='moduledata',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.ProjectData', to_field='project_id'),
        ),
        migrations.AddField(
            model_name='errordata',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.ModuleData', to_field='module_id'),
        ),
    ]
