# Generated by Django 2.0.7 on 2018-07-22 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20180722_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errordata',
            name='error_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='module_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
        ),
    ]
