# Generated by Django 2.0.7 on 2018-08-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20180803_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='errordata',
            name='link_valid',
            field=models.BooleanField(default=False),
        ),
    ]
