# Generated by Django 2.0.7 on 2018-08-04 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_errordata_link_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cluster_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sample.ClusterData', to_field='cluster_id'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='module_id',
            field=models.ForeignKey(default='1.1.1', on_delete=django.db.models.deletion.CASCADE, to='sample.ModuleData', to_field='module_id'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='project_id',
            field=models.ForeignKey(default='1.1', on_delete=django.db.models.deletion.CASCADE, to='sample.ProjectData', to_field='project_id'),
        ),
    ]
