# Generated by Django 2.0.7 on 2018-08-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20180804_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='clusterdata',
            name='cluster_id',
            field=models.CharField(default='C1', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='errordata',
            name='error_id',
            field=models.CharField(default='C1.P1.M1.E1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='module_id',
            field=models.CharField(default='C1.P1.M1', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='project_id',
            field=models.CharField(default='C1.P1', max_length=7, unique=True),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
